name: Run Backend and Frontend Tests and Deploy
on:
  push:
    branches: [main]
env:
  MONGO_URI: mongodb://127.0.0.1:27017/test
  FRONTEND_URL: http://localhost:3000
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REACT_APP_API_BASE_URL: http://localhost:5000
jobs:
  jest-cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('**/cypress.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Load Database with Test Data
        run: |
          cd backend
          node dbtest.js

      - name: Start Backend Server
        run: |
          cd backend
          node app.js &

      - name: Start Frontend Server
        run: |
          cd frontend
          npm start &

      - name: Run Jest Tests
        run: |
          cd backend
          npx jest --runInBand

      - name: Load Database with Frontend Test Data
        run: |
          cd backend
          node createProcessTestData.js

      - name: Run Cypress Tests
        run: |
          cd frontend
          npx cypress run

  deploy:
    needs: jest-cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

      - name: Deploy Backend to Render
        env:
          deploy_url: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
