name: Run Frontend Tests and Deploy
on:
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
        
      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('**/cypress.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "latest"

      - name: Load Database
        run: |
          cd backend
          node dbtest.js

      - name: Start Backend Server
        run: |
          cd backend
          node server.js &
          
      - name: Start Frontend Server
        run: |
          cd frontend
          npm start &

      - name: Run Cypress Tests
        run: |
          cd frontend
          npx cypress run

  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
