name: Run Frontend Tests and Deploy
on:
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear Cache
        run: rm -rf ./frontend/node_modules/.cache
        working-directory: ./frontend

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Start Server
        run: npm start &
        working-directory: ./frontend

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend

  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
