name: Run Frontend Tests and Deploy
on:
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
        
      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('**/cypress.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Start Server
        run: |
          cd frontend
          npm start &

      - name: Run Cypress Tests
        run: |
          cd frontend
          npx cypress run

  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
